# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aws_sdb_bare}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paolo Negri"]
  s.date = %q{2011-03-05}
  s.email = %q{hungryblank@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "aws_sdb_bare.gemspec",
     "lib/aws_sdb_bare.rb",
     "lib/aws_sdb_bare/request.rb",
     "lib/aws_sdb_bare/response.rb",
     "test/aws_sdb_request_template_test.rb",
     "test/aws_sdb_request_test.rb",
     "test/aws_sdb_response_test.rb",
     "test/samples/responses.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/hungryblank/aws_sdb_bare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Amazon AWS SDB SimpleDB client library, low level and http lib agnostic}
  s.test_files = [
    "test/test_helper.rb",
     "test/aws_sdb_request_test.rb",
     "test/samples/responses.rb",
     "test/aws_sdb_response_test.rb",
     "test/aws_sdb_request_template_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

